/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ds1_javafx_login;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {

	public static void main(String[] args) {
        launch(args);
    }
	
	@Override
	public void start(Stage primaryStage) {
		//Janela do Windows 
		primaryStage.setTitle("Tela de Login");
	        
	     primaryStage.show();
	     
////////////////////////////////////////////////////////////////	     
	     
	     //Criando a tela
	     BorderPane screen = new BorderPane();
	     //
	     StackPane top = new StackPane();
	     top.setPrefSize(200, 65);
	     //
	     GridPane centermain = new GridPane();
	     
	     screen.setTop(top);
	     screen.setCenter(centermain);
	     
	     top.setStyle("-fx-background-color: #51C256; -fx-border-style: solid;-fx-border-width: 5; -fx-border-color: transparent transparent #00C909 transparent;");
	     centermain.setStyle("-fx-background-color: black");
	     
	     Scene scene = new Scene(screen, 600, 300);
	     primaryStage.setScene(scene);
	     
////////////////////////////////////////////////////////////////
	     
	     //Criado as coisas na tela  	     
	     //////////////////////////////////////////////////
	     Text toptitle1 = new Text("Login dos");
	     toptitle1.setFont(Font.font(20));
	     												//
	     Text toptitle2 = new Text("H A C K E R M A N S");
	     toptitle2.setFont(Font.font(20));
	     toptitle2.setFill(Color.DARKORCHID);
	     												//
	     top.setAlignment(toptitle1, Pos.TOP_CENTER);
	     top.setAlignment(toptitle2, Pos.BOTTOM_CENTER);
	     top.getChildren().addAll(toptitle1, toptitle2);
	     //////////////////////////////////////////////////	     
	     
	     //////////////////////////////////////////////////
	     Label namelabel = new Label("Insira seu nome");
	     namelabel.setStyle("-fx-text-fill: white");
	     namelabel.setFont(Font.font(13));
	     												//
	     TextField namefield = new TextField();
	     namefield.setPrefWidth(200);
	     namefield.setStyle("-fx-background-color: #51C256");
	     												//
	     Label passlabel = new Label("Insira sua senha");
	     passlabel.setFont(Font.font(13));
	     passlabel.setStyle("-fx-text-fill: white");
	     												//
	     PasswordField passfield = new PasswordField();
	     passfield.setPrefWidth(200);
	     passfield.setStyle("-fx-background-color: #51C256");
	     
	     												//
	     centermain.add(namelabel, 0, 1);
	     centermain.add(namefield, 0, 2);
	     centermain.add(passlabel, 0, 3);
	     centermain.add(passfield, 0, 4);
	     
	     centermain.setPadding(new Insets(10, 0, 0, 20));
	     centermain.setVgap(10);
	     //////////////////////////////////////////////////
	     
	     Button btn = new Button("Logar");
	     btn.setStyle("-fx-text-fill: white;-fx-background-color: #51C256");
	     
	     centermain.add(btn, 0, 5);
	     
////////////////////////////////////////////////////////////////
	     
	}
		
}
